
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmyqiplgjcaxpnojdxmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhteXFpcGxnamNheHBub2pkeG1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjQ4MjksImV4cCI6MjA1ODgwMDgyOX0.tzxkW_UrwoRP5P1WI8AtH_L92qXbVRsv8TZK-s3AaFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define interfaces for the newly created tables
export interface ClientMessage {
  id: string;
  client_id: string;
  sender_id: string;
  is_from_client: boolean;
  message: string;
  attachment_url?: string;
  attachment_type?: string;
  is_read: boolean;
  created_at: Date | string;
}

export interface Resource {
  id: string;
  title: string;
  description?: string;
  type: string;
  url: string;
  created_at: Date | string;
}

export interface Video {
  id: string;
  title: string;
  description?: string;
  youtube_id: string;
  created_at: Date | string;
}

export interface Offer {
  id: string;
  title: string;
  description?: string;
  discount_percentage?: number;
  valid_until: Date | string;
  code?: string;
  created_at: Date | string;
}
